# Ansible should run this after all the infrastructure is destroyed by Terraform.
# It should clean up all resources not managed by Terraform, such as the S3 state
# bucket and any others created in the 000_bootstrap.yml playbook. i.e. it should
# reverse everything from that playbook.

---
- name: Teardown initial resources
  hosts: localhost
  connection: local
  gather_facts: False

  vars_files:
    - vars/example-environment.yml

  tasks:
  - name: Delete root S3 state bucket
    s3_bucket:
      name: "{{ lookup('env', 'STATE_BUCKET') }}"
      aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
      aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
      state: absent
      force: yes

  - name: Delete DynamoDB Lock Table
    dynamodb_table:
      name: "{{ lookup('env', 'DYNAMO_BACKEND_TABLE') }}"
      aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
      aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
      state: absent
